import type { ResourceMapperField } from 'n8n-workflow';

export const slideMappings: Record<string, ResourceMapperField> = {
    ENABLED: {
        id: 'enabled',
        displayName: 'Enabled',
        defaultMatch: false,
        canBeUsedToMatch: false,
        required: false,
        display: true,
        type: 'boolean',
    },
    DURATION: {
        id: 'duration',
        displayName: 'Duration',
        defaultMatch: false,
        canBeUsedToMatch: false,
        required: false,
        display: true,
        type: 'number',
    },
    POSITION: {
        id: 'position',
        displayName: 'Position',
        defaultMatch: false,
        canBeUsedToMatch: false,
        required: false,
        display: true,
        type: 'number',
    },
    DELEGATE_DURATION: {
        id: 'delegateDuration',
        displayName: 'Delegate Duration',
        defaultMatch: false,
        canBeUsedToMatch: false,
        required: false,
        display: true,
        type: 'boolean',
    },
    SCHEDULING: {
        id: 'scheduling',
        displayName: 'Scheduling Type',
        defaultMatch: false,
        canBeUsedToMatch: false,
        required: false,
        display: true,
        type: 'options',
        options: [
            {
                name: 'Loop',
                value: 'loop',
            },
            {
                name: 'Date Time',
                value: 'datetime',
            },
            {
                name: 'In Week',
                value: 'inweek',
            },
        ],
    },
    SCHEDULING_CRON: {
        id: 'scheduling_cron',
        displayName: 'Scheduling Type',
        defaultMatch: false,
        canBeUsedToMatch: false,
        required: false,
        display: true,
        type: 'options',
        options: [
            {
                name: 'Date Time',
                value: 'datetime',
            },
            {
                name: 'Cron',
                value: 'cron',
            },
        ],
    },
    DATETIME_START: {
        id: 'datetime_start',
        displayName: 'Start Date Time',
        defaultMatch: false,
        canBeUsedToMatch: false,
        required: false,
        display: true,
        type: 'string',
    },
    DATETIME_END: {
        id: 'datetime_end',
        displayName: 'End Date Time',
        defaultMatch: false,
        canBeUsedToMatch: false,
        required: false,
        display: true,
        type: 'string',
    },
    CRON_START: {
        id: 'cron_start',
        displayName: 'Cron Start Expression',
        defaultMatch: false,
        canBeUsedToMatch: false,
        required: false,
        display: true,
        type: 'string',
    },
    CRON_END: {
        id: 'cron_end',
        displayName: 'Cron End Expression',
        defaultMatch: false,
        canBeUsedToMatch: false,
        required: false,
        display: true,
        type: 'string',
    },
    DAY_START: {
        id: 'day_start',
        displayName: 'Start Day',
        defaultMatch: false,
        canBeUsedToMatch: false,
        required: false,
        display: true,
        type: 'number',
    },
    TIME_START: {
        id: 'time_start',
        displayName: 'Start Time',
        defaultMatch: false,
        canBeUsedToMatch: false,
        required: false,
        display: true,
        type: 'string',
    },
    DAY_END: {
        id: 'day_end',
        displayName: 'End Day',
        defaultMatch: false,
        canBeUsedToMatch: false,
        required: false,
        display: true,
        type: 'number',
    },
    TIME_END: {
        id: 'time_end',
        displayName: 'End Time',
        defaultMatch: false,
        canBeUsedToMatch: false,
        required: false,
        display: true,
        type: 'string',
    },
}